backend:
  name: github
  repo: randrewsimcdi/docc

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "MarkdownPage"
    label: "Documentation Page"
    folder: "content/docs"
    create: true
    slug: "{{description}}"
        encoding: "ascii"
        clean_accents: true
        sanitize_replacement: "-"
    fields:
      - {label: "Description", name: "description", widget: "string",required: false}
      - {label: "Sidebar", name: "sidebar", widget: "string"}
      - {label: "Prev", name: "prev", widget: "string"}
      - {label: "Next", name: "next", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}


      